In [9]:
data = {
  "_id": "1-889fd444-e543-47f2-9104-a94504b3e888",
  "player_ids": [
    "8f411492-8a71-4bee-a42d-30961aa448f2",
    "eeac2a93-a74f-4922-999d-e9e3ac37bbad",
    "0c2729dc-6759-4a9a-9884-ef1fac446a7d",
    "f364b3d5-8ee1-465c-92f8-a3fcfa13c05b",
    "535b1d8b-1800-44fa-9f8a-85a67a083194",
    "61fad0c5-473e-4dfe-aba1-1dab3afe4d72",
    "245f7052-b832-47b9-afff-867716ece487",
    "374ed655-fbd2-450a-83e3-de15eba368b1",
    "72b3947d-e493-4638-b812-58169e9a4332",
    "b8848d1b-4bc3-4521-bbf5-eeeca74e3df6"
  ],
  "timestamp": {
    "started_at": 1788214167,
    "finished_at": 1788216033
  }
}

In [10]:
import polars as pl
from pipeline.orch import getdata

client = getdata()
client.connect_db(
    'localhost', 27017
)

data = list(client.alters.find({}))

In [11]:
df = pl.DataFrame(data).explode('player_ids').unnest('timestamp')

/tmp/ipykernel_6749/4065549699.py:1: DeprecationWarning: In Polars 2.0, the default behavior for `empty_as_null` will change to `False`. To keep the current behavior, explicitly set `empty_as_null=True`.
  df = pl.DataFrame(data).explode('player_ids').unnest('timestamp')

In [12]:
agg_df = df.group_by("player_ids").agg(
    pl.col('_id').alias('match_ids'),
    pl.col('started_at').max().alias('max_started_at'),
    (pl.col('started_at').min().alias('min_started_at') - 2592000)
)

agg_df.to_dicts()

[{'player_ids': 'bdf5e42d-fe7f-46c8-85cb-aa8ed7dfa174',
  'match_ids': ['1-97049e62-c2e7-4673-8508-e82ce3be6731'],
  'max_started_at': 1785884341,
  'min_started_at': 1783292341},
 {'player_ids': 'dec0b03f-3ec0-4d18-a2d8-bc46a7781946',
  'match_ids': ['1-128833e8-85ca-464a-8d78-c1b58c070dbd'],
  'max_started_at': 1788473544,
  'min_started_at': 1785881544},
 {'player_ids': 'ac8013d7-79fc-4887-9dc9-4dfe3ae504b7',
  'match_ids': ['1-8311ff50-30a3-4871-84df-f38b7779832b'],
  'max_started_at': 1786307814,
  'min_started_at': 1783715814},
 {'player_ids': '412cea42-9afb-432d-aabb-3f1651fe231b',
  'match_ids': ['1-d1f949a2-f9cc-4a44-a75d-ea05eadea78b'],
  'max_started_at': 1788277203,
  'min_started_at': 1785685203},
 {'player_ids': '74fd8d8c-1863-40a6-94de-a8a0d37fe1c5',
  'match_ids': ['1-7d3e0753-3e1c-4e09-a533-0c83768301f9',
   '1-9ea6f325-a9b9-4105-b97e-0e0861fa4960',
   '1-548f3bf4-d213-42a1-97c9-1ad99b224c1e',
   '1-0e42b27d-5e88-4a4c-851a-b1de74a7c61b'],
  'max_started_at': 1788804796,
  'min_started_at': 1779553828},
 {'player_ids': 'f90f72db-ef18-4d9a-bf14-a1b53cf5cd66',
  'match_ids': ['1-397f6a31-1707-4abb-9f94-cf10a787f23c'],
  'max_started_at': 1785547087,
  'min_started_at': 1782955087},
 {'player_ids': '8c91e996-b186-41d5-81f1-a5388e1c0629',
  'match_ids': ['1-3386711a-f2fe-43bb-b039-587770c36c33'],
  'max_started_at': 1786541183,
  'min_started_at': 1783949183},
 {'player_ids': 'd2d50f57-0e6a-4fe3-82d1-a56338aa5ee2',
  'match_ids': ['1-f4f2c2ff-01b7-493e-882a-f00ad23fbc62'],
  'max_started_at': 1783616406,
  'min_started_at': 1781024406},
 {'player_ids': '628bb108-fb61-4878-8564-15460a0ef348',
  'match_ids': ['1-a97399f9-f061-4715-bb85-0f45b91346a7'],
  'max_started_at': 1784235238,
  'min_started_at': 1781643238},
 {'player_ids': 'c28e5004-a35a-4407-a9e4-d6c8dd2c7f34',
  'match_ids': ['1-37ea0b36-2b86-4e16-a941-3eab462d5269'],
  'max_started_at': 1789214281,
  'min_started_at': 1786622281},
 {'player_ids': '24e4fed3-c3ca-42b5-85f3-556b7bf3c8d2',
  'match_ids': ['1-469d08fa-cd03-4b89-b3e5-d380d5a2138c'],
  'max_started_at': 1781898612,
  'min_started_at': 1779306612},
 {'player_ids': '704b19e6-9d51-415c-8452-9b934d51b186',
  'match_ids': ['1-910803d0-a6de-42fd-b946-a18223186198'],
  'max_started_at': 1787877937,
  'min_started_at': 1785285937},
 {'player_ids': 'a9458431-e033-4d8e-913e-f4421931051d',
  'match_ids': ['1-41c04dd9-6494-44ec-bb62-118a4e87edb4',
   '1-6e6f143d-b27f-46d0-ba8a-12eb41bfc54d',
   '1-adca69fb-3a9b-4f61-a4c0-94317409de20',
   '1-f31a1246-283f-4591-8f80-6ffec909b90c',
   '1-5c9f2ec4-cd36-42bf-ae37-145a18ed7279',
   '1-ca12dade-22de-4410-b5be-9572a565b7a2',
   '1-06b9bdcd-d3bd-4605-8f39-1ff7957e38ee'],
  'max_started_at': 1789517740,
  'min_started_at': 1779240855},
 {'player_ids': 'df282f58-acda-42f6-9011-eb6b0c4f1c2b',
  'match_ids': ['1-234d2bb7-5d46-4db3-b599-d4659f75a433'],
  'max_started_at': 1787485784,
  'min_started_at': 1784893784},
 {'player_ids': '1d488964-776a-4ea8-b56d-e18fffca610f',
  'match_ids': ['1-256e588a-206b-48cf-a592-8de0da3d55c2'],
  'max_started_at': 1788806474,
  'min_started_at': 1786214474},
 {'player_ids': '86dc3324-b696-4668-8291-1c08aa479cac',
  'match_ids': ['1-30eb82da-e918-415d-b3ee-586677eec8e1',
   '1-616e9cf1-8b5d-4bc5-bf94-d6b8fb989b06'],
  'max_started_at': 1788128558,
  'min_started_at': 1784933515},
 {'player_ids': 'a6268a65-fdd9-4631-882a-0f30d0183386',
  'match_ids': ['1-662767c6-7e02-4035-9743-9de4b24304f5'],
  'max_started_at': 1789001096,
  'min_started_at': 1786409096},
 {'player_ids': '79254c34-3c46-4d6f-a609-0995dbdb0afb',
  'match_ids': ['1-797a8a92-bdd0-4918-9e05-0ed7baefa210',
   '1-c69577ce-789b-4642-8c01-7b2e6b72569d'],
  'max_started_at': 1787684387,
  'min_started_at': 1780353482},
 {'player_ids': 'c7b95cd5-d6eb-4f72-991b-a01f3d223267',
  'match_ids': ['1-4f870e66-56bd-4c90-9f0a-84cd18258f54'],
  'max_started_at': 1788843519,
  'min_started_at': 1786251519},
 {'player_ids': '6cc04cd7-72b4-467d-ae2c-27c74a48eb41',
  'match_ids': ['1-ab075152-485c-44e0-9ec6-2b6181921dc6'],
  'max_started_at': 1787693947,
  'min_started_at': 1785101947},
 {'player_ids': '4940b568-41b5-4a88-9ae6-a8f7da4aef49',
  'match_ids': ['1-1cc6d0f9-f801-4305-a318-6cd2b483fd63'],
  'max_started_at': 1784634154,
  'min_started_at': 1782042154},
 {'player_ids': '222b9982-39b9-448c-b295-6e8ec01bff81',
  'match_ids': ['1-c1f9ebfd-4a59-42a5-8cfd-690989318b12'],
  'max_started_at': 1783208881,
  'min_started_at': 1780616881},
 {'player_ids': '4f16359e-bb60-4ae9-aadc-f00e8abbf752',
  'match_ids': ['1-0cb3cf07-1aa3-4789-82c8-60025db33cbb',
   '1-195587e2-786e-4b5a-b754-cdaf5f8947b8'],
  'max_started_at': 1784030308,
  'min_started_at': 1781109989},
 {'player_ids': 'd5fc5282-b49c-418c-80df-ac72169b46e8',
  'match_ids': ['1-d861fb37-c414-40cc-bf34-fe9be8ee1978'],
  'max_started_at': 1788615835,
  'min_started_at': 1786023835},
 {'player_ids': '9bfb53bf-01e4-401c-92da-bc1e6f932e98',
  'match_ids': ['1-dfd9d5ae-6912-42b3-b800-e039b947b482',
   '1-3245ee2b-0fb1-4628-b22e-27507fd15ce3',
   '1-bf1fbcb6-707d-4ab8-88e6-9e30e029b94e',
   '1-6de855d4-a097-4fa5-9e8b-4a18abcd95d8',
   '1-65b8119a-c2f8-4617-abfa-15f90e45fa3b'],
  'max_started_at': 1786904001,
  'min_started_at': 1780156499},
 {'player_ids': 'a536bfd5-7c44-460c-a2e4-1db15687c563',
  'match_ids': ['1-7bc053bb-7adc-44c4-9287-7a44ac072704'],
  'max_started_at': 1782145005,
  'min_started_at': 1779553005},
 {'player_ids': 'a3fa3c8b-9258-4e94-abab-4dee22bd5c0d',
  'match_ids': ['1-4f1de3dc-0b0a-4a81-9e43-dde5f2348fb0'],
  'max_started_at': 1787941207,
  'min_started_at': 1785349207},
 {'player_ids': '07ca8e8b-6af9-41d7-9da4-d4c29d3b5817',
  'match_ids': ['1-a405781c-33ed-4401-afb5-af3a0aec67be'],
  'max_started_at': 1785669727,
  'min_started_at': 1783077727},
 {'player_ids': 'f91b19ab-1c18-4bc5-baea-d952f56470c6',
  'match_ids': ['1-59c622d5-5f87-44a1-bd51-532163630727',
   '1-05fc986d-7bc8-4952-9e74-cdb12e4faa91'],
  'max_started_at': 1787449686,
  'min_started_at': 1784141773},
 {'player_ids': 'cba28449-87de-4b03-9c3e-f57c9e5213bf',
  'match_ids': ['1-a5affc12-8603-4d3e-bd3c-b8b692bc1092'],
  'max_started_at': 1786819770,
  'min_started_at': 1784227770},
 {'player_ids': '49a59927-01f5-4c85-8bd3-e7311304fd73',
  'match_ids': ['1-3a8168db-32cd-4c44-8b15-4f3d92488c06',
   '1-eb6e9b8b-e7c8-43d1-bb7e-e8af58f826c1'],
  'max_started_at': 1787094815,
  'min_started_at': 1783186162},
 {'player_ids': '2e315c3c-2e0e-46c7-b014-3fc3afd935f2',
  'match_ids': ['1-0441b561-2190-4e95-ba5c-f1e949a39de7',
   '1-0ae97dc9-a1e6-4a49-8cda-be086e38436c',
   '1-fbc6c563-8cba-452a-a7d3-c999cb399d77',
   '1-032d51b2-4021-4a26-8bf9-29f066b57aff',
   '1-6d822c7c-63ce-4b20-8491-f53c27e16b6b'],
  'max_started_at': 1784815788,
  'min_started_at': 1779784595},
 {'player_ids': '6ef8120f-9cbb-4945-93d7-3113f88f1bec',
  'match_ids': ['1-fc382085-2ca4-4114-ad19-21a938810876'],
  'max_started_at': 1782431478,
  'min_started_at': 1779839478},
 {'player_ids': '41b8177b-5118-4589-bee7-ec33714cad56',
  'match_ids': ['1-65657933-8e0f-4d54-82f1-31428bdc378f'],
  'max_started_at': 1789406113,
  'min_started_at': 1786814113},
 {'player_ids': '80d90c98-e12b-4c03-9247-c65519d54606',
  'match_ids': ['1-2e60ee92-e470-4ac0-af53-910e8d1e375c',
   '1-d708499f-94e2-4da3-b110-8683ba637d44'],
  'max_started_at': 1783117820,
  'min_started_at': 1780188073},
 {'player_ids': 'c0882fe4-e0d4-451e-8c43-9f641a546a9b',
  'match_ids': ['1-f31bdff9-d108-4488-88ce-65551d63d34b'],
  'max_started_at': 1782570195,
  'min_started_at': 1779978195},
 {'player_ids': '3c208aa5-3ef9-4d6e-b2a5-8ddc489310c6',
  'match_ids': ['1-78d23fe4-58ff-49e8-877d-ce4f96a7db4a'],
  'max_started_at': 1786388297,
  'min_started_at': 1783796297},
 {'player_ids': '1a148bb8-9c6d-498a-a00e-835a58b2eb8c',
  'match_ids': ['1-e9b4bfd3-d38a-4677-aba8-b72d43781e67'],
  'max_started_at': 1784587655,
  'min_started_at': 1781995655},
 {'player_ids': 'd5d847f8-fcae-41ea-be2b-cff9c56f8a0b',
  'match_ids': ['1-c371f728-56b8-4f84-9f76-0bac7fce4a43'],
  'max_started_at': 1782763765,
  'min_started_at': 1780171765},
 {'player_ids': '0804589d-6e22-4846-bf4d-14b32c42513e',
  'match_ids': ['1-5398e109-d849-4877-9204-cf9616b3d8f5'],
  'max_started_at': 1789223497,
  'min_started_at': 1786631497},
 {'player_ids': '323fb3d7-7288-435d-b314-4ab2157112aa',
  'match_ids': ['1-3e55e19b-4ae8-4401-80ac-7e19d3925e99'],
  'max_started_at': 1789056251,
  'min_started_at': 1786464251},
 {'player_ids': '297b3038-49a0-4e19-8b29-4f7b151356bc',
  'match_ids': ['1-fcb9c367-61a5-4d8c-988e-83cc440ee080',
   '1-9a2d5d4d-ccf7-4545-b5fe-d2fe08a2f7ee'],
  'max_started_at': 1789308971,
  'min_started_at': 1785537808},
 {'player_ids': '5a1b76e4-6ed9-4b4c-acab-1c12ae2f3a73',
  'match_ids': ['1-da8811e9-3e1d-492a-a837-a1bf7d54f25e'],
  'max_started_at': 1787088937,
  'min_started_at': 1784496937},
 {'player_ids': '725068de-f1e3-453b-9c04-d57a0ccb0ab2',
  'match_ids': ['1-d80f6b48-1676-4b54-809a-5f85c138278a',
   '1-dc9eda1f-5297-4608-8091-3510f9a515dd',
   '1-6ce00a23-e893-418a-8393-cfa4facecdc9'],
  'max_started_at': 1787971415,
  'min_started_at': 1783656535},
 {'player_ids': 'd09140e5-510a-4e67-89db-4df8e5878999',
  'match_ids': ['1-a92f0973-4964-4726-b94a-583178baeb9f'],
  'max_started_at': 1784159868,
  'min_started_at': 1781567868},
 {'player_ids': '276f214a-ac49-4d81-a616-5c2a70962420',
  'match_ids': ['1-57c08476-b8de-4cf9-a008-3c4ac899ba38',
   '1-c77899cd-fd0e-4970-9296-2ab05baa60ec',
   '1-8ae9170d-f321-4a4f-b358-9afb1126d3e2',
   '1-5a1b3ac2-134e-4c2e-8958-8aad5c60ed34',
   '1-4e37eb3f-2e61-48cd-b9f1-2838734b8aec'],
  'max_started_at': 1789384611,
  'min_started_at': 1780507410},
 {'player_ids': '7c433a8f-50b2-4922-aa1b-eb139af75562',
  'match_ids': ['1-7956685c-2b43-4b3e-9d3b-4e5185a76ff0',
   '1-9a2e9a1e-fcc6-4927-b3f7-45bab3ed6644'],
  'max_started_at': 1783125288,
  'min_started_at': 1780185200},
 {'player_ids': 'f60bc9c7-2c92-4631-ac60-cd189795fc7c',
  'match_ids': ['1-57f5a495-8c3b-4b01-82da-a4c53c0a5572',
   '1-3449945b-7fc1-4f46-9836-bb2040b2405f'],
  'max_started_at': 1787760262,
  'min_started_at': 1779991219},
 {'player_ids': 'c6108ea7-7c04-4cfd-bd96-48810c57cd8c',
  'match_ids': ['1-44d14bc1-a990-42cc-8181-61421cd19af2'],
  'max_started_at': 1786970005,
  'min_started_at': 1784378005},
 {'player_ids': 'd8ab4f6e-6389-45ec-b396-4a982fcd2566',
  'match_ids': ['1-44c2f487-30a5-4c08-8c69-b2d1b5c7163e'],
  'max_started_at': 1788981451,
  'min_started_at': 1786389451},
 {'player_ids': '34a08187-f226-483f-95b4-54425110a325',
  'match_ids': ['1-a1567a28-ff8f-48c1-9cdb-c954df40bd4c'],
  'max_started_at': 1787824795,
  'min_started_at': 1785232795},
 {'player_ids': '5ac146c6-f9ca-4fcb-9e08-64c67316ca88',
  'match_ids': ['1-47d5d17a-295b-4fe4-bddf-a202ddbc7e0f'],
  'max_started_at': 1787704015,
  'min_started_at': 1785112015},
 {'player_ids': '1c30cc6a-9c52-4854-a814-0e860e420c17',
  'match_ids': ['1-6549be98-66e2-4f21-b05d-94fb011d817a'],
  'max_started_at': 1787971582,
  'min_started_at': 1785379582},
 {'player_ids': '2cb533cb-9084-4d99-924e-f1c36597f2d2',
  'match_ids': ['1-f40b259e-8f79-46ac-8acb-484f77c17bab',
   '1-be14a8c8-2341-4c15-8482-8b37f355eda6',
   '1-4f77f872-4e47-4882-8280-c5ef5db6089f',
   '1-533f0c68-d7a7-456a-b1c7-3962ea3bd1e6',
   '1-19567ea7-00fc-4ff7-ad0f-448919b5b8cc'],
  'max_started_at': 1788180524,
  'min_started_at': 1782020435},
 {'player_ids': '7053a9ff-77b5-4eec-b270-202384810c01',
  'match_ids': ['1-a0065a46-1d4a-4be0-8b63-f862d3a58003'],
  'max_started_at': 1786229370,
  'min_started_at': 1783637370},
 {'player_ids': '8b389c21-8b4e-4b66-98bf-63c50e3e6b49',
  'match_ids': ['1-fc382085-2ca4-4114-ad19-21a938810876'],
  'max_started_at': 1782431478,
  'min_started_at': 1779839478},
 {'player_ids': '86492cea-e84d-486f-9895-c7d3719fbd86',
  'match_ids': ['1-1750e213-ba3b-4993-a278-96c51822d41d',
   '1-6fbb19a7-e357-42e6-87fc-72b37e2ae376'],
  'max_started_at': 1785965236,
  'min_started_at': 1782868696},
 {'player_ids': '4366b684-154a-4e7c-82f6-97f7269e8aa7',
  'match_ids': ['1-7c84ff53-bc65-459b-ada0-c063b8c86ba9',
   '1-0f8100e2-6d17-4753-a87c-2654ef3148e7',
   '1-becdbc8a-76ad-4ba3-8c2c-b2d47072d69d',
   '1-7629ce39-baa1-4742-a27e-3467319ae106',
   '1-888408e1-2afd-40c2-97a3-6729b5e1b421',
   '1-a7bdd57e-68d4-4da7-8298-f5bcbf80ddfa',
   '1-28990cdf-1c5d-404a-ae51-0ef479cf4f6f',
   '1-1b432473-9808-4f03-add9-0baa64aea4d3',
   '1-aafe5767-3840-4a19-9ca2-b80a398e97a4',
   '1-2c51665e-a3ea-4df1-82e6-da2b93bdd672',
   '1-a22ae532-03c0-4a30-b204-b29a52bef45e',
   '1-572e0dd9-e014-4961-ac65-4a5d1195f7f1',
   '1-e4bbb1aa-4593-4a3e-96df-730ccb400504',
   '1-4dba9e38-5116-4aa7-8a45-7055ec000a90',
   '1-958a4ffb-d7b1-418c-aa4a-54895887b04d',
   '1-3490eea9-fec6-4f86-a00f-6baba9fe05d5',
   '1-7c545082-fec5-4699-807d-171ce1e274bd',
   '1-98b9cd8d-9f44-4b3f-b9c2-1c7e4243b855',
   '1-c81e2434-7a7f-4bc4-a07a-8a1e55173d5d',
   '1-4392f20c-69de-4888-bbe9-87ab7d81c226',
   '1-ef5965be-bbb1-47f4-851c-8b95d54f9b8c',
   '1-15e977ba-4d02-4928-a38d-c7d33bfda528',
   '1-282054ba-47a4-4974-8afe-0bb32964d70d',
   '1-fa943797-3ab0-433d-ad15-76c62841e3e1',
   '1-88d545bb-5551-4d63-b707-12ac3da57e04',
   '1-17153912-bd7f-44bf-aaa6-6651449c8397',
   '1-d7e2b7fe-a1f4-485c-85d8-75284919af7b',
   '1-d7fcab19-439b-4f07-b290-74d1208a7c0d',
   '1-6e7bbf26-f621-42e5-84dc-c4dda79a67f3',
   '1-2d1f919a-02e6-4dfb-85b6-5a7f39f18083',
   '1-1854d36c-a606-4c81-ba9f-f7dbea75dfc1',
   '1-8b5ca5e5-b96c-422f-8285-403ffce49987',
   '1-20ba3e16-5549-4917-927c-84e14d37394a',
   '1-bfa6b42d-36f0-4ee4-9c56-58037b9ce950',
   '1-41dd6fce-2301-4508-95f6-41dda46db257',
   '1-decd0a92-fd7b-438e-86ae-7a9a9d807956',
   '1-b52ea150-bd52-4d94-9587-de34524548a8',
   '1-19b48d49-ac7a-4f84-8d44-2077ddea3d89',
   '1-0e29bdd1-459b-49fb-8d45-092a38a68b2d'],
  'max_started_at': 1787464703,
  'min_started_at': 1780431164},
 {'player_ids': '56f08981-d701-49e3-bee9-3958f12c6f54',
  'match_ids': ['1-11113920-02b5-4d54-9186-cf466752f175'],
  'max_started_at': 1782512379,
  'min_started_at': 1779920379},
 {'player_ids': 'd07a7fdb-9499-4d79-bd53-ce2028103781',
  'match_ids': ['1-31f97113-d298-4616-8514-a49ad8d907a6'],
  'max_started_at': 1786796955,
  'min_started_at': 1784204955},
 {'player_ids': '73e68b66-3f5f-44d1-875b-aeca84eb8caa',
  'match_ids': ['1-5010fa4a-04e1-4ecb-b20f-198c23560f33'],
  'max_started_at': 1785935771,
  'min_started_at': 1783343771},
 {'player_ids': 'eeaa3dbc-08db-45ef-bf61-94d1038b0135',
  'match_ids': ['1-17af0a65-c450-4334-9be4-4b3d4c867a11',
   '1-25a5a4d6-f691-4e3d-8cc8-da4a14a44406',
   '1-3dcd1f2b-46e0-4a34-a854-ebaab16b2cc9',
   '1-067e94c6-cdbc-4002-81f9-93e2e1f73e91',
   '1-4bfaf182-385f-41ef-aa1c-129477ea86f4',
   '1-afbebffa-e219-4079-a80f-331b4ac0aadb',
   '1-9a4832e1-ba10-4bc7-b450-71146c5bcff0'],
  'max_started_at': 1788694689,
  'min_started_at': 1783319936},
 {'player_ids': '939dd5c1-5ffe-4816-b15f-cb188efa3662',
  'match_ids': ['1-526a2965-364a-42d4-8762-decfb6f782cd',
   '1-0b56741c-1599-4de0-ace6-a12679d9a0a1'],
  'max_started_at': 1789041389,
  'min_started_at': 1781712675},
 {'player_ids': 'ce2066d8-2cb9-4a9c-920e-04f169ba73bf',
  'match_ids': ['1-d7e67d44-7cf3-4aaf-a27b-d4d27a39f0cf'],
  'max_started_at': 1783431342,
  'min_started_at': 1780839342},
 {'player_ids': 'dbb6861e-2b02-4262-81be-39de81778761',
  'match_ids': ['1-5c5de0c2-7ec2-44e9-898a-106fb6f72829'],
  'max_started_at': 1784464764,
  'min_started_at': 1781872764},
 {'player_ids': 'c74570a2-09cf-4f82-83b2-fffb84ded6cd',
  'match_ids': ['1-ad1af650-9865-4607-8e9f-85d50179a3ff'],
  'max_started_at': 1784311436,
  'min_started_at': 1781719436},
 {'player_ids': 'ebd85e1c-618a-4dc4-8186-3ef174149a68',
  'match_ids': ['1-bca2ce96-a1c5-4a44-865c-9a45c03d3bab'],
  'max_started_at': 1782000721,
  'min_started_at': 1779408721},
 {'player_ids': '2c3b0a08-7d6e-486f-a66a-21ca0f8a54a0',
  'match_ids': ['1-2cb67c74-5290-451d-ab9f-051ac86f0af5'],
  'max_started_at': 1786487698,
  'min_started_at': 1783895698},
 {'player_ids': 'ecf5e96c-e823-4e22-bccf-caae95eabcd3',
  'match_ids': ['1-4344bf5b-23ed-45a4-beea-346cfc39cb10'],
  'max_started_at': 1783029175,
  'min_started_at': 1780437175},
 {'player_ids': 'f4a31a0c-6c14-4ce3-ae53-a18776703cef',
  'match_ids': ['1-07f10c6e-7e7c-4b93-b922-e8744af5db31'],
  'max_started_at': 1786474437,
  'min_started_at': 1783882437},
 {'player_ids': 'a176d5fe-09d2-45bf-be36-9e84a7b59a2e',
  'match_ids': ['1-50f206de-6c62-46ab-aad7-14c17072c869'],
  'max_started_at': 1781898740,
  'min_started_at': 1779306740},
 {'player_ids': '3508c5db-4f25-40b5-9aa4-6f4bedb33507',
  'match_ids': ['1-5ef218e7-cec3-4159-b47b-3364cab65d4d'],
  'max_started_at': 1787828763,
  'min_started_at': 1785236763},
 {'player_ids': 'e38579d1-d44a-4a84-95ce-04c4f32baf14',
  'match_ids': ['1-990231e6-2b1d-41e2-836b-16f9ad480bcf'],
  'max_started_at': 1788836389,
  'min_started_at': 1786244389},
 {'player_ids': '4255957b-3eae-4563-bab5-adef99658351',
  'match_ids': ['1-8e6cdc73-752b-46c0-b156-5476559add1c'],
  'max_started_at': 1787500332,
  'min_started_at': 1784908332},
 {'player_ids': '5f0b5aa9-fdd3-45f3-ae05-9cd6c4695747',
  'match_ids': ['1-82682275-89f9-4c0b-8756-83867d15bfcc'],
  'max_started_at': 1787770123,
  'min_started_at': 1785178123},
 {'player_ids': '76710402-22f0-41a7-b080-a66baff537ce',
  'match_ids': ['1-1eed4143-eacc-4630-b0d1-e9b0b6a6c242'],
  'max_started_at': 1786306356,
  'min_started_at': 1783714356},
 {'player_ids': '74fae313-e7bd-4c6b-96a5-6edc82080112',
  'match_ids': ['1-6f24f084-3457-4341-bc36-dabb2f65b26b'],
  'max_started_at': 1789120712,
  'min_started_at': 1786528712},
 {'player_ids': 'e2f10366-b245-4402-975d-902d48290331',
  'match_ids': ['1-3f28f424-708e-45bc-b1b1-2df60634ea47'],
  'max_started_at': 1787078907,
  'min_started_at': 1784486907},
 {'player_ids': 'b29f7bf6-436f-4958-b205-bac9798d9805',
  'match_ids': ['1-af5c0351-4d81-468a-b338-715911617a60'],
  'max_started_at': 1784914899,
  'min_started_at': 1782322899},
 {'player_ids': '9972067a-9349-4ecd-b110-6ab933116a57',
  'match_ids': ['1-56b2eae0-cdce-4b28-9313-1c07cf314ecf',
   '1-0c7506f1-7c09-4f79-993d-5412aead8451',
   '1-c206d097-13ae-4971-8afa-1367ab3d177c',
   '1-97a675ad-0c76-4883-8a47-fb3138278ed9'],
  'max_started_at': 1788821425,
  'min_started_at': 1779315400},
 {'player_ids': '806fb2df-1f2f-45bc-bbf7-b058e350779d',
  'match_ids': ['1-831469fa-92ef-4fdd-8bfd-e9af93dccf8c',
   '1-116a18eb-53fa-4338-b387-aec8c8527750'],
  'max_started_at': 1783471621,
  'min_started_at': 1779557418},
 {'player_ids': '6215784e-5499-48e4-a85b-044c880d2a10',
  'match_ids': ['1-cf5aa78d-9e80-4f3e-b110-7a6590c68ded'],
  'max_started_at': 1788005653,
  'min_started_at': 1785413653},
 {'player_ids': 'd7bde67b-eb29-44ac-b154-0dc2b101ffd1',
  'match_ids': ['1-bd1bec6f-932c-428d-ac9a-aca67785cb3b'],
  'max_started_at': 1786214651,
  'min_started_at': 1783622651},
 {'player_ids': '6350f58c-57a3-4d3f-b4b5-7112a285083b',
  'match_ids': ['1-444539c0-9ecb-43c7-bd12-1e7dc8f5faed'],
  'max_started_at': 1785509161,
  'min_started_at': 1782917161},
 {'player_ids': '80bdedff-9bdf-4f64-a523-55eba772621e',
  'match_ids': ['1-fcb9c367-61a5-4d8c-988e-83cc440ee080'],
  'max_started_at': 1789308971,
  'min_started_at': 1786716971},
 {'player_ids': 'e8b3aedf-ed5c-49b9-92f5-d3b1e3d9b125',
  'match_ids': ['1-6a1f38de-bacf-4a9a-96f9-03c78b4bd836'],
  'max_started_at': 1788769202,
  'min_started_at': 1786177202},
 {'player_ids': 'c6b18e69-6a17-42cf-b45f-e43c9bdea92a',
  'match_ids': ['1-f250a02b-ac11-41aa-a387-aa2c7b13f835'],
  'max_started_at': 1786058251,
  'min_started_at': 1783466251},
 {'player_ids': '05b121f6-1f55-4ab7-a425-50c48fad4465',
  'match_ids': ['1-8be9d662-17fe-48e7-ae02-e3c03d0a00e2',
   '1-1c001da0-b455-4160-88c0-253c787d87a5'],
  'max_started_at': 1788797919,
  'min_started_at': 1780691598},
 {'player_ids': 'e2d3b67f-25db-41f5-8355-0f09e8c4a6ce',
  'match_ids': ['1-26ed76e8-2efe-4be8-96c2-7c08bda1335d'],
  'max_started_at': 1788927386,
  'min_started_at': 1786335386},
 {'player_ids': '7e2073fe-b574-4ec8-b87d-e50db7dc6965',

In [13]:
agg_df.to_dicts()

[{'player_ids': 'bdf5e42d-fe7f-46c8-85cb-aa8ed7dfa174',
  'match_ids': ['1-97049e62-c2e7-4673-8508-e82ce3be6731'],
  'max_started_at': 1785884341,
  'min_started_at': 1783292341},
 {'player_ids': 'dec0b03f-3ec0-4d18-a2d8-bc46a7781946',
  'match_ids': ['1-128833e8-85ca-464a-8d78-c1b58c070dbd'],
  'max_started_at': 1788473544,
  'min_started_at': 1785881544},
 {'player_ids': 'ac8013d7-79fc-4887-9dc9-4dfe3ae504b7',
  'match_ids': ['1-8311ff50-30a3-4871-84df-f38b7779832b'],
  'max_started_at': 1786307814,
  'min_started_at': 1783715814},
 {'player_ids': '412cea42-9afb-432d-aabb-3f1651fe231b',
  'match_ids': ['1-d1f949a2-f9cc-4a44-a75d-ea05eadea78b'],
  'max_started_at': 1788277203,
  'min_started_at': 1785685203},
 {'player_ids': '74fd8d8c-1863-40a6-94de-a8a0d37fe1c5',
  'match_ids': ['1-7d3e0753-3e1c-4e09-a533-0c83768301f9',
   '1-9ea6f325-a9b9-4105-b97e-0e0861fa4960',
   '1-548f3bf4-d213-42a1-97c9-1ad99b224c1e',
   '1-0e42b27d-5e88-4a4c-851a-b1de74a7c61b'],
  'max_started_at': 1788804796,
  'min_started_at': 1779553828},
 {'player_ids': 'f90f72db-ef18-4d9a-bf14-a1b53cf5cd66',
  'match_ids': ['1-397f6a31-1707-4abb-9f94-cf10a787f23c'],
  'max_started_at': 1785547087,
  'min_started_at': 1782955087},
 {'player_ids': '8c91e996-b186-41d5-81f1-a5388e1c0629',
  'match_ids': ['1-3386711a-f2fe-43bb-b039-587770c36c33'],
  'max_started_at': 1786541183,
  'min_started_at': 1783949183},
 {'player_ids': 'd2d50f57-0e6a-4fe3-82d1-a56338aa5ee2',
  'match_ids': ['1-f4f2c2ff-01b7-493e-882a-f00ad23fbc62'],
  'max_started_at': 1783616406,
  'min_started_at': 1781024406},
 {'player_ids': '628bb108-fb61-4878-8564-15460a0ef348',
  'match_ids': ['1-a97399f9-f061-4715-bb85-0f45b91346a7'],
  'max_started_at': 1784235238,
  'min_started_at': 1781643238},
 {'player_ids': 'c28e5004-a35a-4407-a9e4-d6c8dd2c7f34',
  'match_ids': ['1-37ea0b36-2b86-4e16-a941-3eab462d5269'],
  'max_started_at': 1789214281,
  'min_started_at': 1786622281},
 {'player_ids': '24e4fed3-c3ca-42b5-85f3-556b7bf3c8d2',
  'match_ids': ['1-469d08fa-cd03-4b89-b3e5-d380d5a2138c'],
  'max_started_at': 1781898612,
  'min_started_at': 1779306612},
 {'player_ids': '704b19e6-9d51-415c-8452-9b934d51b186',
  'match_ids': ['1-910803d0-a6de-42fd-b946-a18223186198'],
  'max_started_at': 1787877937,
  'min_started_at': 1785285937},
 {'player_ids': 'a9458431-e033-4d8e-913e-f4421931051d',
  'match_ids': ['1-41c04dd9-6494-44ec-bb62-118a4e87edb4',
   '1-6e6f143d-b27f-46d0-ba8a-12eb41bfc54d',
   '1-adca69fb-3a9b-4f61-a4c0-94317409de20',
   '1-f31a1246-283f-4591-8f80-6ffec909b90c',
   '1-5c9f2ec4-cd36-42bf-ae37-145a18ed7279',
   '1-ca12dade-22de-4410-b5be-9572a565b7a2',
   '1-06b9bdcd-d3bd-4605-8f39-1ff7957e38ee'],
  'max_started_at': 1789517740,
  'min_started_at': 1779240855},
 {'player_ids': 'df282f58-acda-42f6-9011-eb6b0c4f1c2b',
  'match_ids': ['1-234d2bb7-5d46-4db3-b599-d4659f75a433'],
  'max_started_at': 1787485784,
  'min_started_at': 1784893784},
 {'player_ids': '1d488964-776a-4ea8-b56d-e18fffca610f',
  'match_ids': ['1-256e588a-206b-48cf-a592-8de0da3d55c2'],
  'max_started_at': 1788806474,
  'min_started_at': 1786214474},
 {'player_ids': '86dc3324-b696-4668-8291-1c08aa479cac',
  'match_ids': ['1-30eb82da-e918-415d-b3ee-586677eec8e1',
   '1-616e9cf1-8b5d-4bc5-bf94-d6b8fb989b06'],
  'max_started_at': 1788128558,
  'min_started_at': 1784933515},
 {'player_ids': 'a6268a65-fdd9-4631-882a-0f30d0183386',
  'match_ids': ['1-662767c6-7e02-4035-9743-9de4b24304f5'],
  'max_started_at': 1789001096,
  'min_started_at': 1786409096},
 {'player_ids': '79254c34-3c46-4d6f-a609-0995dbdb0afb',
  'match_ids': ['1-797a8a92-bdd0-4918-9e05-0ed7baefa210',
   '1-c69577ce-789b-4642-8c01-7b2e6b72569d'],
  'max_started_at': 1787684387,
  'min_started_at': 1780353482},
 {'player_ids': 'c7b95cd5-d6eb-4f72-991b-a01f3d223267',
  'match_ids': ['1-4f870e66-56bd-4c90-9f0a-84cd18258f54'],
  'max_started_at': 1788843519,
  'min_started_at': 1786251519},
 {'player_ids': '6cc04cd7-72b4-467d-ae2c-27c74a48eb41',
  'match_ids': ['1-ab075152-485c-44e0-9ec6-2b6181921dc6'],
  'max_started_at': 1787693947,
  'min_started_at': 1785101947},
 {'player_ids': '4940b568-41b5-4a88-9ae6-a8f7da4aef49',
  'match_ids': ['1-1cc6d0f9-f801-4305-a318-6cd2b483fd63'],
  'max_started_at': 1784634154,
  'min_started_at': 1782042154},
 {'player_ids': '222b9982-39b9-448c-b295-6e8ec01bff81',
  'match_ids': ['1-c1f9ebfd-4a59-42a5-8cfd-690989318b12'],
  'max_started_at': 1783208881,
  'min_started_at': 1780616881},
 {'player_ids': '4f16359e-bb60-4ae9-aadc-f00e8abbf752',
  'match_ids': ['1-0cb3cf07-1aa3-4789-82c8-60025db33cbb',
   '1-195587e2-786e-4b5a-b754-cdaf5f8947b8'],
  'max_started_at': 1784030308,
  'min_started_at': 1781109989},
 {'player_ids': 'd5fc5282-b49c-418c-80df-ac72169b46e8',
  'match_ids': ['1-d861fb37-c414-40cc-bf34-fe9be8ee1978'],
  'max_started_at': 1788615835,
  'min_started_at': 1786023835},
 {'player_ids': '9bfb53bf-01e4-401c-92da-bc1e6f932e98',
  'match_ids': ['1-dfd9d5ae-6912-42b3-b800-e039b947b482',
   '1-3245ee2b-0fb1-4628-b22e-27507fd15ce3',
   '1-bf1fbcb6-707d-4ab8-88e6-9e30e029b94e',
   '1-6de855d4-a097-4fa5-9e8b-4a18abcd95d8',
   '1-65b8119a-c2f8-4617-abfa-15f90e45fa3b'],
  'max_started_at': 1786904001,
  'min_started_at': 1780156499},
 {'player_ids': 'a536bfd5-7c44-460c-a2e4-1db15687c563',
  'match_ids': ['1-7bc053bb-7adc-44c4-9287-7a44ac072704'],
  'max_started_at': 1782145005,
  'min_started_at': 1779553005},
 {'player_ids': 'a3fa3c8b-9258-4e94-abab-4dee22bd5c0d',
  'match_ids': ['1-4f1de3dc-0b0a-4a81-9e43-dde5f2348fb0'],
  'max_started_at': 1787941207,
  'min_started_at': 1785349207},
 {'player_ids': '07ca8e8b-6af9-41d7-9da4-d4c29d3b5817',
  'match_ids': ['1-a405781c-33ed-4401-afb5-af3a0aec67be'],
  'max_started_at': 1785669727,
  'min_started_at': 1783077727},
 {'player_ids': 'f91b19ab-1c18-4bc5-baea-d952f56470c6',
  'match_ids': ['1-59c622d5-5f87-44a1-bd51-532163630727',
   '1-05fc986d-7bc8-4952-9e74-cdb12e4faa91'],
  'max_started_at': 1787449686,
  'min_started_at': 1784141773},
 {'player_ids': 'cba28449-87de-4b03-9c3e-f57c9e5213bf',
  'match_ids': ['1-a5affc12-8603-4d3e-bd3c-b8b692bc1092'],
  'max_started_at': 1786819770,
  'min_started_at': 1784227770},
 {'player_ids': '49a59927-01f5-4c85-8bd3-e7311304fd73',
  'match_ids': ['1-3a8168db-32cd-4c44-8b15-4f3d92488c06',
   '1-eb6e9b8b-e7c8-43d1-bb7e-e8af58f826c1'],
  'max_started_at': 1787094815,
  'min_started_at': 1783186162},
 {'player_ids': '2e315c3c-2e0e-46c7-b014-3fc3afd935f2',
  'match_ids': ['1-0441b561-2190-4e95-ba5c-f1e949a39de7',
   '1-0ae97dc9-a1e6-4a49-8cda-be086e38436c',
   '1-fbc6c563-8cba-452a-a7d3-c999cb399d77',
   '1-032d51b2-4021-4a26-8bf9-29f066b57aff',
   '1-6d822c7c-63ce-4b20-8491-f53c27e16b6b'],
  'max_started_at': 1784815788,
  'min_started_at': 1779784595},
 {'player_ids': '6ef8120f-9cbb-4945-93d7-3113f88f1bec',
  'match_ids': ['1-fc382085-2ca4-4114-ad19-21a938810876'],
  'max_started_at': 1782431478,
  'min_started_at': 1779839478},
 {'player_ids': '41b8177b-5118-4589-bee7-ec33714cad56',
  'match_ids': ['1-65657933-8e0f-4d54-82f1-31428bdc378f'],
  'max_started_at': 1789406113,
  'min_started_at': 1786814113},
 {'player_ids': '80d90c98-e12b-4c03-9247-c65519d54606',
  'match_ids': ['1-2e60ee92-e470-4ac0-af53-910e8d1e375c',
   '1-d708499f-94e2-4da3-b110-8683ba637d44'],
  'max_started_at': 1783117820,
  'min_started_at': 1780188073},
 {'player_ids': 'c0882fe4-e0d4-451e-8c43-9f641a546a9b',
  'match_ids': ['1-f31bdff9-d108-4488-88ce-65551d63d34b'],
  'max_started_at': 1782570195,
  'min_started_at': 1779978195},
 {'player_ids': '3c208aa5-3ef9-4d6e-b2a5-8ddc489310c6',
  'match_ids': ['1-78d23fe4-58ff-49e8-877d-ce4f96a7db4a'],
  'max_started_at': 1786388297,
  'min_started_at': 1783796297},
 {'player_ids': '1a148bb8-9c6d-498a-a00e-835a58b2eb8c',
  'match_ids': ['1-e9b4bfd3-d38a-4677-aba8-b72d43781e67'],
  'max_started_at': 1784587655,
  'min_started_at': 1781995655},
 {'player_ids': 'd5d847f8-fcae-41ea-be2b-cff9c56f8a0b',
  'match_ids': ['1-c371f728-56b8-4f84-9f76-0bac7fce4a43'],
  'max_started_at': 1782763765,
  'min_started_at': 1780171765},
 {'player_ids': '0804589d-6e22-4846-bf4d-14b32c42513e',
  'match_ids': ['1-5398e109-d849-4877-9204-cf9616b3d8f5'],
  'max_started_at': 1789223497,
  'min_started_at': 1786631497},
 {'player_ids': '323fb3d7-7288-435d-b314-4ab2157112aa',
  'match_ids': ['1-3e55e19b-4ae8-4401-80ac-7e19d3925e99'],
  'max_started_at': 1789056251,
  'min_started_at': 1786464251},
 {'player_ids': '297b3038-49a0-4e19-8b29-4f7b151356bc',
  'match_ids': ['1-fcb9c367-61a5-4d8c-988e-83cc440ee080',
   '1-9a2d5d4d-ccf7-4545-b5fe-d2fe08a2f7ee'],
  'max_started_at': 1789308971,
  'min_started_at': 1785537808},
 {'player_ids': '5a1b76e4-6ed9-4b4c-acab-1c12ae2f3a73',
  'match_ids': ['1-da8811e9-3e1d-492a-a837-a1bf7d54f25e'],
  'max_started_at': 1787088937,
  'min_started_at': 1784496937},
 {'player_ids': '725068de-f1e3-453b-9c04-d57a0ccb0ab2',
  'match_ids': ['1-d80f6b48-1676-4b54-809a-5f85c138278a',
   '1-dc9eda1f-5297-4608-8091-3510f9a515dd',
   '1-6ce00a23-e893-418a-8393-cfa4facecdc9'],
  'max_started_at': 1787971415,
  'min_started_at': 1783656535},
 {'player_ids': 'd09140e5-510a-4e67-89db-4df8e5878999',
  'match_ids': ['1-a92f0973-4964-4726-b94a-583178baeb9f'],
  'max_started_at': 1784159868,
  'min_started_at': 1781567868},
 {'player_ids': '276f214a-ac49-4d81-a616-5c2a70962420',
  'match_ids': ['1-57c08476-b8de-4cf9-a008-3c4ac899ba38',
   '1-c77899cd-fd0e-4970-9296-2ab05baa60ec',
   '1-8ae9170d-f321-4a4f-b358-9afb1126d3e2',
   '1-5a1b3ac2-134e-4c2e-8958-8aad5c60ed34',
   '1-4e37eb3f-2e61-48cd-b9f1-2838734b8aec'],
  'max_started_at': 1789384611,
  'min_started_at': 1780507410},
 {'player_ids': '7c433a8f-50b2-4922-aa1b-eb139af75562',
  'match_ids': ['1-7956685c-2b43-4b3e-9d3b-4e5185a76ff0',
   '1-9a2e9a1e-fcc6-4927-b3f7-45bab3ed6644'],
  'max_started_at': 1783125288,
  'min_started_at': 1780185200},
 {'player_ids': 'f60bc9c7-2c92-4631-ac60-cd189795fc7c',
  'match_ids': ['1-57f5a495-8c3b-4b01-82da-a4c53c0a5572',
   '1-3449945b-7fc1-4f46-9836-bb2040b2405f'],
  'max_started_at': 1787760262,
  'min_started_at': 1779991219},
 {'player_ids': 'c6108ea7-7c04-4cfd-bd96-48810c57cd8c',
  'match_ids': ['1-44d14bc1-a990-42cc-8181-61421cd19af2'],
  'max_started_at': 1786970005,
  'min_started_at': 1784378005},
 {'player_ids': 'd8ab4f6e-6389-45ec-b396-4a982fcd2566',
  'match_ids': ['1-44c2f487-30a5-4c08-8c69-b2d1b5c7163e'],
  'max_started_at': 1788981451,
  'min_started_at': 1786389451},
 {'player_ids': '34a08187-f226-483f-95b4-54425110a325',
  'match_ids': ['1-a1567a28-ff8f-48c1-9cdb-c954df40bd4c'],
  'max_started_at': 1787824795,
  'min_started_at': 1785232795},
 {'player_ids': '5ac146c6-f9ca-4fcb-9e08-64c67316ca88',
  'match_ids': ['1-47d5d17a-295b-4fe4-bddf-a202ddbc7e0f'],
  'max_started_at': 1787704015,
  'min_started_at': 1785112015},
 {'player_ids': '1c30cc6a-9c52-4854-a814-0e860e420c17',
  'match_ids': ['1-6549be98-66e2-4f21-b05d-94fb011d817a'],
  'max_started_at': 1787971582,
  'min_started_at': 1785379582},
 {'player_ids': '2cb533cb-9084-4d99-924e-f1c36597f2d2',
  'match_ids': ['1-f40b259e-8f79-46ac-8acb-484f77c17bab',
   '1-be14a8c8-2341-4c15-8482-8b37f355eda6',
   '1-4f77f872-4e47-4882-8280-c5ef5db6089f',
   '1-533f0c68-d7a7-456a-b1c7-3962ea3bd1e6',
   '1-19567ea7-00fc-4ff7-ad0f-448919b5b8cc'],
  'max_started_at': 1788180524,
  'min_started_at': 1782020435},
 {'player_ids': '7053a9ff-77b5-4eec-b270-202384810c01',
  'match_ids': ['1-a0065a46-1d4a-4be0-8b63-f862d3a58003'],
  'max_started_at': 1786229370,
  'min_started_at': 1783637370},
 {'player_ids': '8b389c21-8b4e-4b66-98bf-63c50e3e6b49',
  'match_ids': ['1-fc382085-2ca4-4114-ad19-21a938810876'],
  'max_started_at': 1782431478,
  'min_started_at': 1779839478},
 {'player_ids': '86492cea-e84d-486f-9895-c7d3719fbd86',
  'match_ids': ['1-1750e213-ba3b-4993-a278-96c51822d41d',
   '1-6fbb19a7-e357-42e6-87fc-72b37e2ae376'],
  'max_started_at': 1785965236,
  'min_started_at': 1782868696},
 {'player_ids': '4366b684-154a-4e7c-82f6-97f7269e8aa7',
  'match_ids': ['1-7c84ff53-bc65-459b-ada0-c063b8c86ba9',
   '1-0f8100e2-6d17-4753-a87c-2654ef3148e7',
   '1-becdbc8a-76ad-4ba3-8c2c-b2d47072d69d',
   '1-7629ce39-baa1-4742-a27e-3467319ae106',
   '1-888408e1-2afd-40c2-97a3-6729b5e1b421',
   '1-a7bdd57e-68d4-4da7-8298-f5bcbf80ddfa',
   '1-28990cdf-1c5d-404a-ae51-0ef479cf4f6f',
   '1-1b432473-9808-4f03-add9-0baa64aea4d3',
   '1-aafe5767-3840-4a19-9ca2-b80a398e97a4',
   '1-2c51665e-a3ea-4df1-82e6-da2b93bdd672',
   '1-a22ae532-03c0-4a30-b204-b29a52bef45e',
   '1-572e0dd9-e014-4961-ac65-4a5d1195f7f1',
   '1-e4bbb1aa-4593-4a3e-96df-730ccb400504',
   '1-4dba9e38-5116-4aa7-8a45-7055ec000a90',
   '1-958a4ffb-d7b1-418c-aa4a-54895887b04d',
   '1-3490eea9-fec6-4f86-a00f-6baba9fe05d5',
   '1-7c545082-fec5-4699-807d-171ce1e274bd',
   '1-98b9cd8d-9f44-4b3f-b9c2-1c7e4243b855',
   '1-c81e2434-7a7f-4bc4-a07a-8a1e55173d5d',
   '1-4392f20c-69de-4888-bbe9-87ab7d81c226',
   '1-ef5965be-bbb1-47f4-851c-8b95d54f9b8c',
   '1-15e977ba-4d02-4928-a38d-c7d33bfda528',
   '1-282054ba-47a4-4974-8afe-0bb32964d70d',
   '1-fa943797-3ab0-433d-ad15-76c62841e3e1',
   '1-88d545bb-5551-4d63-b707-12ac3da57e04',
   '1-17153912-bd7f-44bf-aaa6-6651449c8397',
   '1-d7e2b7fe-a1f4-485c-85d8-75284919af7b',
   '1-d7fcab19-439b-4f07-b290-74d1208a7c0d',
   '1-6e7bbf26-f621-42e5-84dc-c4dda79a67f3',
   '1-2d1f919a-02e6-4dfb-85b6-5a7f39f18083',
   '1-1854d36c-a606-4c81-ba9f-f7dbea75dfc1',
   '1-8b5ca5e5-b96c-422f-8285-403ffce49987',
   '1-20ba3e16-5549-4917-927c-84e14d37394a',
   '1-bfa6b42d-36f0-4ee4-9c56-58037b9ce950',
   '1-41dd6fce-2301-4508-95f6-41dda46db257',
   '1-decd0a92-fd7b-438e-86ae-7a9a9d807956',
   '1-b52ea150-bd52-4d94-9587-de34524548a8',
   '1-19b48d49-ac7a-4f84-8d44-2077ddea3d89',
   '1-0e29bdd1-459b-49fb-8d45-092a38a68b2d'],
  'max_started_at': 1787464703,
  'min_started_at': 1780431164},
 {'player_ids': '56f08981-d701-49e3-bee9-3958f12c6f54',
  'match_ids': ['1-11113920-02b5-4d54-9186-cf466752f175'],
  'max_started_at': 1782512379,
  'min_started_at': 1779920379},
 {'player_ids': 'd07a7fdb-9499-4d79-bd53-ce2028103781',
  'match_ids': ['1-31f97113-d298-4616-8514-a49ad8d907a6'],
  'max_started_at': 1786796955,
  'min_started_at': 1784204955},
 {'player_ids': '73e68b66-3f5f-44d1-875b-aeca84eb8caa',
  'match_ids': ['1-5010fa4a-04e1-4ecb-b20f-198c23560f33'],
  'max_started_at': 1785935771,
  'min_started_at': 1783343771},
 {'player_ids': 'eeaa3dbc-08db-45ef-bf61-94d1038b0135',
  'match_ids': ['1-17af0a65-c450-4334-9be4-4b3d4c867a11',
   '1-25a5a4d6-f691-4e3d-8cc8-da4a14a44406',
   '1-3dcd1f2b-46e0-4a34-a854-ebaab16b2cc9',
   '1-067e94c6-cdbc-4002-81f9-93e2e1f73e91',
   '1-4bfaf182-385f-41ef-aa1c-129477ea86f4',
   '1-afbebffa-e219-4079-a80f-331b4ac0aadb',
   '1-9a4832e1-ba10-4bc7-b450-71146c5bcff0'],
  'max_started_at': 1788694689,
  'min_started_at': 1783319936},
 {'player_ids': '939dd5c1-5ffe-4816-b15f-cb188efa3662',
  'match_ids': ['1-526a2965-364a-42d4-8762-decfb6f782cd',
   '1-0b56741c-1599-4de0-ace6-a12679d9a0a1'],
  'max_started_at': 1789041389,
  'min_started_at': 1781712675},
 {'player_ids': 'ce2066d8-2cb9-4a9c-920e-04f169ba73bf',
  'match_ids': ['1-d7e67d44-7cf3-4aaf-a27b-d4d27a39f0cf'],
  'max_started_at': 1783431342,
  'min_started_at': 1780839342},
 {'player_ids': 'dbb6861e-2b02-4262-81be-39de81778761',
  'match_ids': ['1-5c5de0c2-7ec2-44e9-898a-106fb6f72829'],
  'max_started_at': 1784464764,
  'min_started_at': 1781872764},
 {'player_ids': 'c74570a2-09cf-4f82-83b2-fffb84ded6cd',
  'match_ids': ['1-ad1af650-9865-4607-8e9f-85d50179a3ff'],
  'max_started_at': 1784311436,
  'min_started_at': 1781719436},
 {'player_ids': 'ebd85e1c-618a-4dc4-8186-3ef174149a68',
  'match_ids': ['1-bca2ce96-a1c5-4a44-865c-9a45c03d3bab'],
  'max_started_at': 1782000721,
  'min_started_at': 1779408721},
 {'player_ids': '2c3b0a08-7d6e-486f-a66a-21ca0f8a54a0',
  'match_ids': ['1-2cb67c74-5290-451d-ab9f-051ac86f0af5'],
  'max_started_at': 1786487698,
  'min_started_at': 1783895698},
 {'player_ids': 'ecf5e96c-e823-4e22-bccf-caae95eabcd3',
  'match_ids': ['1-4344bf5b-23ed-45a4-beea-346cfc39cb10'],
  'max_started_at': 1783029175,
  'min_started_at': 1780437175},
 {'player_ids': 'f4a31a0c-6c14-4ce3-ae53-a18776703cef',
  'match_ids': ['1-07f10c6e-7e7c-4b93-b922-e8744af5db31'],
  'max_started_at': 1786474437,
  'min_started_at': 1783882437},
 {'player_ids': 'a176d5fe-09d2-45bf-be36-9e84a7b59a2e',
  'match_ids': ['1-50f206de-6c62-46ab-aad7-14c17072c869'],
  'max_started_at': 1781898740,
  'min_started_at': 1779306740},
 {'player_ids': '3508c5db-4f25-40b5-9aa4-6f4bedb33507',
  'match_ids': ['1-5ef218e7-cec3-4159-b47b-3364cab65d4d'],
  'max_started_at': 1787828763,
  'min_started_at': 1785236763},
 {'player_ids': 'e38579d1-d44a-4a84-95ce-04c4f32baf14',
  'match_ids': ['1-990231e6-2b1d-41e2-836b-16f9ad480bcf'],
  'max_started_at': 1788836389,
  'min_started_at': 1786244389},
 {'player_ids': '4255957b-3eae-4563-bab5-adef99658351',
  'match_ids': ['1-8e6cdc73-752b-46c0-b156-5476559add1c'],
  'max_started_at': 1787500332,
  'min_started_at': 1784908332},
 {'player_ids': '5f0b5aa9-fdd3-45f3-ae05-9cd6c4695747',
  'match_ids': ['1-82682275-89f9-4c0b-8756-83867d15bfcc'],
  'max_started_at': 1787770123,
  'min_started_at': 1785178123},
 {'player_ids': '76710402-22f0-41a7-b080-a66baff537ce',
  'match_ids': ['1-1eed4143-eacc-4630-b0d1-e9b0b6a6c242'],
  'max_started_at': 1786306356,
  'min_started_at': 1783714356},
 {'player_ids': '74fae313-e7bd-4c6b-96a5-6edc82080112',
  'match_ids': ['1-6f24f084-3457-4341-bc36-dabb2f65b26b'],
  'max_started_at': 1789120712,
  'min_started_at': 1786528712},
 {'player_ids': 'e2f10366-b245-4402-975d-902d48290331',
  'match_ids': ['1-3f28f424-708e-45bc-b1b1-2df60634ea47'],
  'max_started_at': 1787078907,
  'min_started_at': 1784486907},
 {'player_ids': 'b29f7bf6-436f-4958-b205-bac9798d9805',
  'match_ids': ['1-af5c0351-4d81-468a-b338-715911617a60'],
  'max_started_at': 1784914899,
  'min_started_at': 1782322899},
 {'player_ids': '9972067a-9349-4ecd-b110-6ab933116a57',
  'match_ids': ['1-56b2eae0-cdce-4b28-9313-1c07cf314ecf',
   '1-0c7506f1-7c09-4f79-993d-5412aead8451',
   '1-c206d097-13ae-4971-8afa-1367ab3d177c',
   '1-97a675ad-0c76-4883-8a47-fb3138278ed9'],
  'max_started_at': 1788821425,
  'min_started_at': 1779315400},
 {'player_ids': '806fb2df-1f2f-45bc-bbf7-b058e350779d',
  'match_ids': ['1-831469fa-92ef-4fdd-8bfd-e9af93dccf8c',
   '1-116a18eb-53fa-4338-b387-aec8c8527750'],
  'max_started_at': 1783471621,
  'min_started_at': 1779557418},
 {'player_ids': '6215784e-5499-48e4-a85b-044c880d2a10',
  'match_ids': ['1-cf5aa78d-9e80-4f3e-b110-7a6590c68ded'],
  'max_started_at': 1788005653,
  'min_started_at': 1785413653},
 {'player_ids': 'd7bde67b-eb29-44ac-b154-0dc2b101ffd1',
  'match_ids': ['1-bd1bec6f-932c-428d-ac9a-aca67785cb3b'],
  'max_started_at': 1786214651,
  'min_started_at': 1783622651},
 {'player_ids': '6350f58c-57a3-4d3f-b4b5-7112a285083b',
  'match_ids': ['1-444539c0-9ecb-43c7-bd12-1e7dc8f5faed'],
  'max_started_at': 1785509161,
  'min_started_at': 1782917161},
 {'player_ids': '80bdedff-9bdf-4f64-a523-55eba772621e',
  'match_ids': ['1-fcb9c367-61a5-4d8c-988e-83cc440ee080'],
  'max_started_at': 1789308971,
  'min_started_at': 1786716971},
 {'player_ids': 'e8b3aedf-ed5c-49b9-92f5-d3b1e3d9b125',
  'match_ids': ['1-6a1f38de-bacf-4a9a-96f9-03c78b4bd836'],
  'max_started_at': 1788769202,
  'min_started_at': 1786177202},
 {'player_ids': 'c6b18e69-6a17-42cf-b45f-e43c9bdea92a',
  'match_ids': ['1-f250a02b-ac11-41aa-a387-aa2c7b13f835'],
  'max_started_at': 1786058251,
  'min_started_at': 1783466251},
 {'player_ids': '05b121f6-1f55-4ab7-a425-50c48fad4465',
  'match_ids': ['1-8be9d662-17fe-48e7-ae02-e3c03d0a00e2',
   '1-1c001da0-b455-4160-88c0-253c787d87a5'],
  'max_started_at': 1788797919,
  'min_started_at': 1780691598},
 {'player_ids': 'e2d3b67f-25db-41f5-8355-0f09e8c4a6ce',
  'match_ids': ['1-26ed76e8-2efe-4be8-96c2-7c08bda1335d'],
  'max_started_at': 1788927386,
  'min_started_at': 1786335386},
 {'player_ids': '7e2073fe-b574-4ec8-b87d-e50db7dc6965',

In [14]:
list1= agg_df.select(
    "player_ids",
    pl.col("match_ids").list.len().alias("n_matches"),
).sort("n_matches", descending=True)['player_ids'][50:100]

import requests
import os
from dotenv import load_dotenv

load_dotenv()


API_KEY = os.environ['API_KEY']

for PLAYER_ID in list1:
    #PLAYER_ID = "75065f7e-4cac-4a39-9e0d-617a0293304c"

    url = f"https://open.faceit.com/data/v4/players/{PLAYER_ID}"

    headers = {
        "Authorization": f"Bearer {API_KEY}"
    }

    response = requests.get(url, headers=headers)
    response.raise_for_status()

    player = response.json()

    print("FACEIT name:", player["nickname"])

FACEIT name: Muzz_1
FACEIT name: -Pops1clE-
FACEIT name: Nikoinfinity
FACEIT name: gunsnatcher
FACEIT name: -Neme
FACEIT name: RUSHHHH-
FACEIT name: -Swa_
FACEIT name: Migrane
FACEIT name: 6yar
FACEIT name: -WARDELL
FACEIT name: Jimbo-xD
FACEIT name: Hunaid--
FACEIT name: SKIZZY47
FACEIT name: -Odachi
FACEIT name: rop-
FACEIT name: MoJisuke
FACEIT name: C1S-
FACEIT name: N0INF0
FACEIT name: -ArchNemesis
FACEIT name: Jaanooo1
FACEIT name: 1MMMMMMMMMMM
FACEIT name: ooooooooook
FACEIT name: Pashaaaa-
FACEIT name: ELPUNISHER
FACEIT name: VARLIX
FACEIT name: -Rabb1tz
FACEIT name: ---Rose-
FACEIT name: Lone-Wol7
FACEIT name: -_koi
FACEIT name: -Kayxee-
FACEIT name: --_Jerry_--
FACEIT name: -Tri
FACEIT name: ammaRRRRRRR
FACEIT name: 4rslan-
FACEIT name: ClassicMan_
FACEIT name: DatuMaro
FACEIT name: -420W1CK3D
FACEIT name: R1p999
FACEIT name: iBaaaaaaad
FACEIT name: adnanNn1
FACEIT name: rAiin-
FACEIT name: -_electro-_-
FACEIT name: -protagon1st
FACEIT name: AllOver-
FACEIT name: --BENN--
FACEIT name: Off_scene
FACEIT name: --LM10--
FACEIT name: Half-Life-3
FACEIT name: K4EVER
FACEIT name: -BL4NCO

In [15]:
agg_df.select(
    "player_ids",
    pl.col("match_ids").list.len().alias("n_matches"),
).sort("n_matches", descending=True)[50:100]

shape: (50, 2)
┌─────────────────────────────────┬───────────┐
│ player_ids                      ┆ n_matches │
│ ---                             ┆ ---       │
│ str                             ┆ u32       │
╞═════════════════════════════════╪═══════════╡
│ ce9bb281-3b2d-4ca2-9a26-9b1e0d… ┆ 85        │
│ 5b5bbaa5-2eca-476c-ad17-0dbe50… ┆ 85        │
│ 1a046637-fe13-400c-839f-150adc… ┆ 85        │
│ 64833aaf-85c3-459b-98cd-7d8d58… ┆ 85        │
│ 225fc6b4-91a4-454b-9dd8-a39ac4… ┆ 83        │
│ …                               ┆ …         │
│ cbaeaa1d-7b4a-4cc4-8d28-3c1b56… ┆ 74        │
│ 093ba79a-8e2a-402a-bb3b-74ae3e… ┆ 74        │
│ c789348f-eaee-47f8-848d-48ed9d… ┆ 73        │
│ 06b7679f-49b4-42da-8369-472535… ┆ 73        │
│ 8429bbdd-c338-4537-b7ef-95b471… ┆ 73        │
└─────────────────────────────────┴───────────┘

In [16]:
data = list(client.alters.find({}))
df = pl.DataFrame(data).explode('player_ids').unnest('timestamp')

agg_df = df.group_by("player_ids").agg(
    pl.struct(
        pl.col("_id"),
        pl.col("started_at")
    ).alias("match_ids"),
    pl.col('started_at').max().alias('max_started_at'),
    (pl.col('started_at').min().alias('min_started_at') - 2592000)
)

final_df = agg_df.to_dicts()
final_df[:1]

/tmp/ipykernel_6749/3983081841.py:2: DeprecationWarning: In Polars 2.0, the default behavior for `empty_as_null` will change to `False`. To keep the current behavior, explicitly set `empty_as_null=True`.
  df = pl.DataFrame(data).explode('player_ids').unnest('timestamp')

[{'player_ids': 'fdc2fc1f-b2c5-4b5f-baa9-6170ac9b4362',
  'match_ids': [{'_id': '1-fdd05174-49e2-4712-9a84-2542ad1d4599',
    'started_at': 1787605801}],
  'max_started_at': 1787605801,
  'min_started_at': 1785013801}]

In [17]:
from pympler import asizeof

data_mb = asizeof.asizeof(data) / (1024 ** 2)
final_df_mb = asizeof.asizeof(final_df) / (1024 ** 2)

print(f"data:     {data_mb:.2f} MB")
print(f"final_df: {final_df_mb:.2f} MB")

data:     50.68 MB
final_df: 172.38 MB

In [19]:
import polars as pl
import requests
import os
from dotenv import load_dotenv
from datetime import datetime

load_dotenv()
API_KEY = os.environ["API_KEY"]

top_player = (
    agg_df
    .with_columns(
        pl.col("match_ids").list.len().alias("n_matches")
    )
    .sort("n_matches", descending=True)
    .row(0, named=True)
)

PLAYER_ID = top_player["player_ids"]
MIN_STARTED_AT = top_player["min_started_at"]
MAX_STARTED_AT = top_player["max_started_at"]

url = f"https://open.faceit.com/data/v4/players/{PLAYER_ID}/history"
headers = {"Authorization": f"Bearer {API_KEY}"}

all_matches = []
limit = 100
offset = 0

while offset <= 1000:
    params = {
        "game": "cs2",
        "from": MIN_STARTED_AT,
        "to": MAX_STARTED_AT,
        "limit": limit,
        "offset": offset,
    }

    r = requests.get(url, headers=headers, params=params)
    r.raise_for_status()

    matches = r.json().get("items", [])
    all_matches.extend(matches)

    print(f"offset={offset} -> {len(matches)} matches")

    if len(matches) < limit:
        break

    offset += limit

print("\nPlayer:", PLAYER_ID)
print("Matches in agg_df:", top_player["n_matches"])
print("Min start:", MIN_STARTED_AT, datetime.fromtimestamp(MIN_STARTED_AT))
print("Max start:", MAX_STARTED_AT, datetime.fromtimestamp(MAX_STARTED_AT))
print("Total FACEIT matches returned:", len(all_matches))
print("Unique matches:", len({m["match_id"] for m in all_matches}))

offset=0 -> 100 matches
offset=100 -> 100 matches
offset=200 -> 100 matches
offset=300 -> 100 matches
offset=400 -> 100 matches
offset=500 -> 100 matches
offset=600 -> 100 matches
offset=700 -> 100 matches
offset=800 -> 64 matches

Player: 75065f7e-4cac-4a39-9e0d-617a0293304c
Matches in agg_df: 153
Min start: 1779671085 2026-05-25 05:04:45
Max start: 1789504531 2026-09-16 00:35:31
Total FACEIT matches returned: 864
Unique matches: 864

In [20]:
all_matches

[{'match_id': '1-4f52c127-1de4-408c-a4b6-b48286356f01',
  'game_id': 'cs2',
  'region': 'EU',
  'match_type': '',
  'game_mode': '5v5',
  'max_players': 10,
  'teams_size': 5,
  'teams': {'faction1': {'team_id': 'd9d1a97e-56f4-466c-a272-874e5f2ae369',
    'nickname': 'team_C4pr1corn',
    'avatar': 'https://assets.faceit-cdn.net/avatars/4f5d5e30-7b77-40f7-a655-2094e9ddc999_1551272294700.jpg',
    'type': '',
    'players': [{'player_id': '4f5d5e30-7b77-40f7-a655-2094e9ddc999',
      'nickname': 'C4pr1corn',
      'avatar': 'https://assets.faceit-cdn.net/avatars/4f5d5e30-7b77-40f7-a655-2094e9ddc999_1551272294700.jpg',
      'skill_level': 8,
      'game_player_id': '76561198116406598',
      'game_player_name': 'C4pr1c0rn (Mid)',
      'faceit_url': 'https://www.faceit.com/{lang}/players/C4pr1corn'},
     {'player_id': 'e47f3329-3033-4a11-b43d-7d0ca506518a',
      'nickname': '9999999_',
      'avatar': 'https://distribution.faceit-cdn.net/images/d9fca1e0-c7b9-4fbb-aa36-46b3599ab674.jpg',
      'skill_level': 10,
      'game_player_id': '76561198211381019',
      'game_player_name': 'kookyy.',
      'faceit_url': 'https://www.faceit.com/{lang}/players/9999999_'},
     {'player_id': '6577086d-60db-4e97-9b20-f814b7c693af',
      'nickname': 'ookayiztallr',
      'avatar': 'https://assets.faceit-cdn.net/avatars/6577086d-60db-4e97-9b20-f814b7c693af_1551097295495.jpg',
      'skill_level': 10,
      'game_player_id': '76561198391476296',
      'game_player_name': 'panick',
      'faceit_url': 'https://www.faceit.com/{lang}/players/ookayiztallr'},
     {'player_id': 'c4757568-e353-4447-a34b-ce00dd9dcfdd',
      'nickname': 'fps',
      'avatar': 'https://distribution.faceit-cdn.net/images/423af4c0-6aad-44a5-b512-adcf1a53c1ef.jpg',
      'skill_level': 10,
      'game_player_id': '76561198859290505',
      'game_player_name': 'fps',
      'faceit_url': 'https://www.faceit.com/{lang}/players/fps'},
     {'player_id': '0bc39f9a-d4ab-4d26-85e0-86d81c49ec27',
      'nickname': 'Vaxeee',
      'avatar': 'https://distribution.faceit-cdn.net/images/540def10-216a-475f-9b9c-f7f5e1cd4b30.jpg',
      'skill_level': 9,
      'game_player_id': '76561199186851671',
      'game_player_name': 'Nawaz Sharif',
      'faceit_url': 'https://www.faceit.com/{lang}/players/Vaxeee'}]},
   'faction2': {'team_id': '23ba6d0a-16a4-4b5c-8bff-c73b43bd4258',
    'nickname': 'team_rop-',
    'avatar': 'https://distribution.faceit-cdn.net/images/632b5c1d-4c5b-4ffe-9af8-ec4359773df6.jpg',
    'type': '',
    'players': [{'player_id': '23ba6d0a-16a4-4b5c-8bff-c73b43bd4258',
      'nickname': 'rop-',
      'avatar': 'https://distribution.faceit-cdn.net/images/632b5c1d-4c5b-4ffe-9af8-ec4359773df6.jpg',
      'skill_level': 10,
      'game_player_id': '76561198201263445',
      'game_player_name': 'rop',
      'faceit_url': 'https://www.faceit.com/{lang}/players/rop-'},
     {'player_id': 'd723126d-ca29-4670-a5b4-c4e6ad78495e',
      'nickname': 'Kuf94',
      'avatar': 'https://distribution.faceit-cdn.net/images/ce835a03-6f81-4147-b24c-1cb6f82e65e4.jpg',
      'skill_level': 10,
      'game_player_id': '76561198157452555',
      'game_player_name': 'Tak Sebe Igrochishka',
      'faceit_url': 'https://www.faceit.com/{lang}/players/Kuf94'},
     {'player_id': '75065f7e-4cac-4a39-9e0d-617a0293304c',
      'nickname': 'tyejo',
      'avatar': 'https://distribution.faceit-cdn.net/images/eb7e01a4-62b8-47ef-915a-e06e28e07ca5.jpg',
      'skill_level': 10,
      'game_player_id': '76561198035063267',
      'game_player_name': 'movingdiego',
      'faceit_url': 'https://www.faceit.com/{lang}/players/tyejo'},
     {'player_id': '7e075b1c-b5a1-4743-8412-b2e85f6e9208',
      'nickname': '-aaN',
      'avatar': 'https://distribution.faceit-cdn.net/images/2eb7a046-e733-4a5a-90c9-7ce11f3d9c23.jpg',
      'skill_level': 9,
      'game_player_id': '76561198338006145',
      'game_player_name': 'Tanjirooo',
      'faceit_url': 'https://www.faceit.com/{lang}/players/-aaN'},
     {'player_id': '536ed390-396b-4961-a7c6-4da20110bd09',
      'nickname': '--FaNuU--',
      'avatar': 'https://distribution.faceit-cdn.net/images/e4ff627f-297f-412e-ba95-c676e730cabc.jpeg',
      'skill_level': 10,
      'game_player_id': '76561198362200385',
      'game_player_name': '☠ Fannu',
      'faceit_url': 'https://www.faceit.com/{lang}/players/--FaNuU--'}]}},
  'playing_players': ['4f5d5e30-7b77-40f7-a655-2094e9ddc999',
   'e47f3329-3033-4a11-b43d-7d0ca506518a',
   '6577086d-60db-4e97-9b20-f814b7c693af',
   'c4757568-e353-4447-a34b-ce00dd9dcfdd',
   '0bc39f9a-d4ab-4d26-85e0-86d81c49ec27',
   '23ba6d0a-16a4-4b5c-8bff-c73b43bd4258',
   'd723126d-ca29-4670-a5b4-c4e6ad78495e',
   '75065f7e-4cac-4a39-9e0d-617a0293304c',
   '7e075b1c-b5a1-4743-8412-b2e85f6e9208',
   '536ed390-396b-4961-a7c6-4da20110bd09'],
  'competition_id': '71041d12-e7ad-477b-a29b-4086d51acc24',
  'competition_name': 'Middle East 5v5 Queue',
  'competition_type': 'matchmaking',
  'organizer_id': 'faceit',
  'status': 'finished',
  'started_at': 1789506830,
  'finished_at': 1789509440,
  'results': {'winner': 'faction2', 'score': {'faction1': 10, 'faction2': 13}},
  'faceit_url': 'https://www.faceit.com/{lang}/cs2/room/1-4f52c127-1de4-408c-a4b6-b48286356f01'},
 {'match_id': '1-feaa8570-aed9-48ed-a4e8-5a40817d98eb',
  'game_id': 'cs2',
  'region': 'EU',
  'match_type': '',
  'game_mode': '5v5',
  'max_players': 10,
  'teams_size': 5,
  'teams': {'faction1': {'team_id': 'a5d1c918-7f9e-44ac-9138-c52190e0b0d3',
    'nickname': 'team_ELPUNISHER',
    'avatar': 'https://distribution.faceit-cdn.net/images/d5e3c182-f8b8-478c-a58b-9780084b7176.jpg',
    'type': '',
    'players': [{'player_id': '11afcf9e-36bb-499d-b652-6cec8609ce0e',
      'nickname': '-Kayxee-',
      'avatar': 'https://distribution.faceit-cdn.net/images/ed5236b7-120a-4614-bb53-c3406aa86fed.jpg',
      'skill_level': 10,
      'game_player_id': '76561198858309841',
      'game_player_name': '-Kayxee-',
      'faceit_url': 'https://www.faceit.com/{lang}/players/-Kayxee-'},
     {'player_id': '68a7f15b-d1ec-4a66-953c-b6776fe8a5cb',
      'nickname': '-ZoHaiB-',
      'avatar': '',
      'skill_level': 10,
      'game_player_id': '76561199503936440',
      'game_player_name': 'Professional Qasai',
      'faceit_url': 'https://www.faceit.com/{lang}/players/-ZoHaiB-'},
     {'player_id': 'd07e9bdb-ff6c-48cc-80f3-c75b9388cdff',
      'nickname': 'HACKERRRRRRR',
      'avatar': 'https://distribution.faceit-cdn.net/images/043137ec-2714-4ef4-b4da-7738bb3c6ecb.jpg',
      'skill_level': 10,
      'game_player_id': '76561198873441799',
      'game_player_name': 'RestoreMySoul',
      'faceit_url': 'https://www.faceit.com/{lang}/players/HACKERRRRRRR'},
     {'player_id': '33ee5446-e137-4bc3-a3f7-97a91c316aa5',
      'nickname': 'suskuni',
      'avatar': 'https://distribution.faceit-cdn.net/images/94099d57-f4e3-4c2c-9c1f-2f42582c5840.jpeg',
      'skill_level': 10,
      'game_player_id': '76561198151729172',
      'game_player_name': 'pope',
      'faceit_url': 'https://www.faceit.com/{lang}/players/suskuni'},
     {'player_id': 'a5d1c918-7f9e-44ac-9138-c52190e0b0d3',
      'nickname': 'ELPUNISHER',
      'avatar': 'https://distribution.faceit-cdn.net/images/d5e3c182-f8b8-478c-a58b-9780084b7176.jpg',
      'skill_level': 9,
      'game_player_id': '76561198750903234',
      'game_player_name': 'omaralseyed10',
      'faceit_url': 'https://www.faceit.com/{lang}/players/ELPUNISHER'}]},
   'faction2': {'team_id': '23ba6d0a-16a4-4b5c-8bff-c73b43bd4258',
    'nickname': 'team_rop-',
    'avatar': 'https://distribution.faceit-cdn.net/images/632b5c1d-4c5b-4ffe-9af8-ec4359773df6.jpg',
    'type': '',
    'players': [{'player_id': '23ba6d0a-16a4-4b5c-8bff-c73b43bd4258',
      'nickname': 'rop-',
      'avatar': 'https://distribution.faceit-cdn.net/images/632b5c1d-4c5b-4ffe-9af8-ec4359773df6.jpg',
      'skill_level': 10,
      'game_player_id': '76561198201263445',
      'game_player_name': 'rop',
      'faceit_url': 'https://www.faceit.com/{lang}/players/rop-'},
     {'player_id': 'd723126d-ca29-4670-a5b4-c4e6ad78495e',
      'nickname': 'Kuf94',
      'avatar': 'https://distribution.faceit-cdn.net/images/ce835a03-6f81-4147-b24c-1cb6f82e65e4.jpg',
      'skill_level': 10,
      'game_player_id': '76561198157452555',
      'game_player_name': 'Tak Sebe Igrochishka',
      'faceit_url': 'https://www.faceit.com/{lang}/players/Kuf94'},
     {'player_id': '75065f7e-4cac-4a39-9e0d-617a0293304c',
      'nickname': 'tyejo',
      'avatar': 'https://distribution.faceit-cdn.net/images/eb7e01a4-62b8-47ef-915a-e06e28e07ca5.jpg',
      'skill_level': 10,
      'game_player_id': '76561198035063267',
      'game_player_name': 'movingdiego',
      'faceit_url': 'https://www.faceit.com/{lang}/players/tyejo'},
     {'player_id': '4c96247f-4f0c-4b7e-956c-5e92e0048b53',
      'nickname': 'Skullaimer',
      'avatar': 'https://distribution.faceit-cdn.net/images/f0690d96-6254-4fb6-b27c-6e7657e6027f.jpg',
      'skill_level': 10,
      'game_player_id': '76561198253491801',
      'game_player_name': '$kull 4im3r',
      'faceit_url': 'https://www.faceit.com/{lang}/players/Skullaimer'},
     {'player_id': '5132c5f8-b411-4d5f-9314-9c84959800c7',
      'nickname': '--ScarFace_',
      'avatar': 'https://distribution.faceit-cdn.net/images/aaba97f7-e19e-4876-9291-8a39195bb4d6.jpeg',
      'skill_level': 0,
      'game_player_id': '76561198065405147',
      'game_player_name': 'Tony Montanna',
      'faceit_url': 'https://www.faceit.com/{lang}/players/--ScarFace_'}]}},
  'playing_players': ['11afcf9e-36bb-499d-b652-6cec8609ce0e',
   '68a7f15b-d1ec-4a66-953c-b6776fe8a5cb',
   'd07e9bdb-ff6c-48cc-80f3-c75b9388cdff',
   '33ee5446-e137-4bc3-a3f7-97a91c316aa5',
   'a5d1c918-7f9e-44ac-9138-c52190e0b0d3',
   '23ba6d0a-16a4-4b5c-8bff-c73b43bd4258',
   'd723126d-ca29-4670-a5b4-c4e6ad78495e',
   '75065f7e-4cac-4a39-9e0d-617a0293304c',
   '4c96247f-4f0c-4b7e-956c-5e92e0048b53',
   '5132c5f8-b411-4d5f-9314-9c84959800c7'],
  'competition_id': '71041d12-e7ad-477b-a29b-4086d51acc24',
  'competition_name': 'Middle East 5v5 Queue',
  'competition_type': 'matchmaking',
  'organizer_id': 'faceit',
  'status': 'finished',
  'started_at': 1789504531,
  'finished_at': 1789506584,
  'results': {'winner': 'faction1', 'score': {'faction1': 13, 'faction2': 7}},
  'faceit_url': 'https://www.faceit.com/{lang}/cs2/room/1-feaa8570-aed9-48ed-a4e8-5a40817d98eb'},
 {'match_id': '1-d647c6e1-cb1e-4602-9aca-6fbc4892c22d',
  'game_id': 'cs2',
  'region': 'EU',
  'match_type': '',
  'game_mode': '5v5',
  'max_players': 10,
  'teams_size': 5,
  'teams': {'faction1': {'team_id': '23ba6d0a-16a4-4b5c-8bff-c73b43bd4258',
    'nickname': 'team_rop-',
    'avatar': 'https://distribution.faceit-cdn.net/images/632b5c1d-4c5b-4ffe-9af8-ec4359773df6.jpg',
    'type': '',
    'players': [{'player_id': '824a4edd-6f8f-423d-85c3-5be9f94f0fee',
      'nickname': '-Maddyy',
      'avatar': 'https://distribution.faceit-cdn.net/images/12cca74f-598a-44eb-bb4c-7ad1783f6b2b.jpg',
      'skill_level': 10,
      'game_player_id': '76561199034126256',
      'game_player_name': '☜☯☞ M A D D Y ☜☯☞',
      'faceit_url': 'https://www.faceit.com/{lang}/players/-Maddyy'},
     {'player_id': 'ce2a11cf-1df5-4169-83d4-67fb7ad41e98',
      'nickname': '-_electro-_-',
      'avatar': 'https://distribution.faceit-cdn.net/images/e9a74655-7e72-4f88-b5c6-3308c01595e1.jpg',
      'skill_level': 10,
      'game_player_id': '76561198254212130',
      'game_player_name': 'electro',
      'faceit_url': 'https://www.faceit.com/{lang}/players/-_electro-_-'},
     {'player_id': '23ba6d0a-16a4-4b5c-8bff-c73b43bd4258',
      'nickname': 'rop-',
      'avatar': 'https://distribution.faceit-cdn.net/images/632b5c1d-4c5b-4ffe-9af8-ec4359773df6.jpg',
      'skill_level': 10,
      'game_player_id': '76561198201263445',
      'game_player_name': 'rop',
      'faceit_url': 'https://www.faceit.com/{lang}/players/rop-'},
     {'player_id': 'd723126d-ca29-4670-a5b4-c4e6ad78495e',
      'nickname': 'Kuf94',
      'avatar': 'https://distribution.faceit-cdn.net/images/ce835a03-6f81-4147-b24c-1cb6f82e65e4.jpg',
      'skill_level': 10,
      'game_player_id': '76561198157452555',
      'game_player_name': 'Tak Sebe Igrochishka',
      'faceit_url': 'https://www.faceit.com/{lang}/players/Kuf94'},
     {'player_id': '75065f7e-4cac-4a39-9e0d-617a0293304c',
      'nickname': 'tyejo',
      'avatar': 'https://distribution.faceit-cdn.net/images/eb7e01a4-62b8-47ef-915a-e06e28e07ca5.jpg',
      'skill_level': 10,
      'game_player_id': '76561198035063267',
      'game_player_name': 'movingdiego',
      'faceit_url': 'https://www.faceit.com/{lang}/players/tyejo'}]},
   'faction2': {'team_id': '153b3362-31b3-425a-a505-1a0c19aaf25a',
    'nickname': 'team_Peps1m',
    'avatar': 'https://assets.faceit-cdn.net/avatars/153b3362-31b3-425a-a505-1a0c19aaf25a_1550505735392.jpg',
    'type': '',
    'players': [{'player_id': '153b3362-31b3-425a-a505-1a0c19aaf25a',
      'nickname': 'Peps1m',
      'avatar': 'https://assets.faceit-cdn.net/avatars/153b3362-31b3-425a-a505-1a0c19aaf25a_1550505735392.jpg',
      'skill_level': 10,
      'game_player_id': '76561198066828435',
      'game_player_name': 'Peps',
      'faceit_url': 'https://www.faceit.com/{lang}/players/Peps1m'},
     {'player_id': '6809ed6f-c343-4ca5-b99e-3061761a60e7',
      'nickname': 'aimer7',
      'avatar': 'https://distribution.faceit-cdn.net/images/69cc3439-fa61-4087-b5a6-4f18c73707c9.jpg',
      'skill_level': 10,
      'game_player_id': '76561197964314872',
      'game_player_name': 'lostt',
      'faceit_url': 'https://www.faceit.com/{lang}/players/aimer7'},
     {'player_id': 'ccfe0112-1a5d-4f9f-a2f5-aa3e4e79be30',
      'nickname': 'Bom7md',
      'avatar': 'https://distribution.faceit-cdn.net/images/f18785ed-61f3-4aea-87df-16f522f01344.jpg',
      'skill_level': 10,
      'game_player_id': '76561198368377384',
      'game_player_name': 'Ace',
      'faceit_url': 'https://www.faceit.com/{lang}/players/Bom7md'},
     {'player_id': 'c6d00cf0-551e-4a12-b9d1-71ce63265d07',
      'nickname': 'Demha',
      'avatar': 'https://distribution.faceit-cdn.net/images/bdddd821-d650-421b-bef2-3029e2b59bb9.jpg',
      'skill_level': 10,
      'game_player_id': '76561198166578900',
      'game_player_name': 'Demha',
      'faceit_url': 'https://www.faceit.com/{lang}/players/Demha'},
     {'player_id': '7a9e4412-054f-474b-af03-ab9d4d7253c2',
      'nickname': 'SPOT00',
      'avatar': 'https://distribution.faceit-cdn.net/images/34f6bb56-07ea-4ad8-a906-7c08e61e86c9.jpg',
      'skill_level': 10,
      'game_player_id': '76561198744195985',
      'game_player_name': 'Zywo0',
      'faceit_url': 'https://www.faceit.com/{lang}/players/SPOT00'}]}},
  'playing_players': ['824a4edd-6f8f-423d-85c3-5be9f94f0fee',
   'ce2a11cf-1df5-4169-83d4-67fb7ad41e98',
   '23ba6d0a-16a4-4b5c-8bff-c73b43bd4258',
   'd723126d-ca29-4670-a5b4-c4e6ad78495e',
   '75065f7e-4cac-4a39-9e0d-617a0293304c',
   '153b3362-31b3-425a-a505-1a0c19aaf25a',
   '6809ed6f-c343-4ca5-b99e-3061761a60e7',
   'ccfe0112-1a5d-4f9f-a2f5-aa3e4e79be30',
   'c6d00cf0-551e-4a12-b9d1-71ce63265d07',
   '7a9e4412-054f-474b-af03-ab9d4d7253c2'],
  'competition_id': '71041d12-e7ad-477b-a29b-4086d51acc24',
  'competition_name': 'Middle East 5v5 Queue',
  'competition_type': 'matchmaking',
  'organizer_id': 'faceit',
  'status': 'finished',
  'started_at': 1789501859,
  'finished_at': 1789503960,
  'results': {'winner': 'faction2', 'score': {'faction2': 13, 'faction1': 7}},
  'faceit_url': 'https://www.faceit.com/{lang}/cs2/room/1-d647c6e1-cb1e-4602-9aca-6fbc4892c22d'},
 {'match_id': '1-f68c4de6-8b45-478f-9160-3ad697e4f374',
  'game_id': 'cs2',
  'region': 'EU',
  'match_type': '',
  'game_mode': '5v5',
  'max_players': 10,
  'teams_size': 5,
  'teams': {'faction2': {'team_id': '23ba6d0a-16a4-4b5c-8bff-c73b43bd4258',
    'nickname': 'team_rop-',
    'avatar': 'https://distribution.faceit-cdn.net/images/632b5c1d-4c5b-4ffe-9af8-ec4359773df6.jpg',
    'type': '',
    'players': [{'player_id': '824a4edd-6f8f-423d-85c3-5be9f94f0fee',
      'nickname': '-Maddyy',
      'avatar': 'https://distribution.faceit-cdn.net/images/12cca74f-598a-44eb-bb4c-7ad1783f6b2b.jpg',
      'skill_level': 10,
      'game_player_id': '76561199034126256',
      'game_player_name': '☜☯☞ M A D D Y ☜☯☞',
      'faceit_url': 'https://www.faceit.com/{lang}/players/-Maddyy'},
     {'player_id': 'ce2a11cf-1df5-4169-83d4-67fb7ad41e98',
      'nickname': '-_electro-_-',
      'avatar': 'https://distribution.faceit-cdn.net/images/e9a74655-7e72-4f88-b5c6-3308c01595e1.jpg',
      'skill_level': 10,
      'game_player_id': '76561198254212130',
      'game_player_name': 'electro',
      'faceit_url': 'https://www.faceit.com/{lang}/players/-_electro-_-'},
     {'player_id': '23ba6d0a-16a4-4b5c-8bff-c73b43bd4258',
      'nickname': 'rop-',
      'avatar': 'https://distribution.faceit-cdn.net/images/632b5c1d-4c5b-4ffe-9af8-ec4359773df6.jpg',
      'skill_level': 10,
      'game_player_id': '76561198201263445',
      'game_player_name': 'rop',
      'faceit_url': 'https://www.faceit.com/{lang}/players/rop-'},
     {'player_id': 'd723126d-ca29-4670-a5b4-c4e6ad78495e',
      'nickname': 'Kuf94',
      'avatar': 'https://distribution.faceit-cdn.net/images/ce835a03-6f81-4147-b24c-1cb6f82e65e4.jpg',
      'skill_level': 10,
      'game_player_id': '76561198157452555',
      'game_player_name': 'Tak Sebe Igrochishka',
      'faceit_url': 'https://www.faceit.com/{lang}/players/Kuf94'},
     {'player_id': '75065f7e-4cac-4a39-9e0d-617a0293304c',
      'nickname': 'tyejo',
      'avatar': 'https://distribution.faceit-cdn.net/images/eb7e01a4-62b8-47ef-915a-e06e28e07ca5.jpg',
      'skill_level': 10,
      'game_player_id': '76561198035063267',
      'game_player_name': 'movingdiego',
      'faceit_url': 'https://www.faceit.com/{lang}/players/tyejo'}]},
   'faction1': {'team_id': '9c35ebf3-d62d-4510-b5c8-d59bf7d3701a',
    'nickname': 'team_VARLIX',
    'avatar': 'https://distribution.faceit-cdn.net/images/926a536b-8820-4476-a3c9-aa8bcef6adbc.jpg',
    'type': '',
    'players': [{'player_id': '7d90d3a5-9aa6-4a34-aafa-3bd70e51d7de',
      'nickname': 'Sas-Ak',
      'avatar': 'https://distribution.faceit-cdn.net/images/6432fe43-3191-4364-8595-228793066134.jpg',
      'skill_level': 10,
      'game_player_id': '76561198841425249',
      'game_player_name': 'SaS_Ak',
      'faceit_url': 'https://www.faceit.com/{lang}/players/Sas-Ak'},
     {'player_id': '9c35ebf3-d62d-4510-b5c8-d59bf7d3701a',
      'nickname': 'VARLIX',
      'avatar': 'https://distribution.faceit-cdn.net/images/926a536b-8820-4476-a3c9-aa8bcef6adbc.jpg',
      'skill_level': 10,
      'game_player_id': '76561198234145164',
      'game_player_name': 'VARLIX',
      'faceit_url': 'https://www.faceit.com/{lang}/players/VARLIX'},
     {'player_id': '56c68c2a-3934-4ff1-83b9-3c6e690f6ebb',
      'nickname': 'Wa7sh',
      'avatar': 'https://distribution.faceit-cdn.net/images/d12c1d37-2876-4d3d-9998-e1a41c60606f.jpeg',
      'skill_level': 10,
      'game_player_id': '76561197984243480',
      'game_player_name': 'wa7sh.',
      'faceit_url': 'https://www.faceit.com/{lang}/players/Wa7sh'},
     {'player_id': '0be34787-fc22-48c5-b026-63a40eff66b2',
      'nickname': 'KRR-KRR',
      'avatar': 'https://distribution.faceit-cdn.net/images/7d667742-11ce-4e01-bf79-d499889b5010.jpg',
      'skill_level': 8,
      'game_player_id': '76561199642634551',
      'game_player_name': 'teeeeeko',
      'faceit_url': 'https://www.faceit.com/{lang}/players/KRR-KRR'},
     {'player_id': '7b3bbc47-dd92-4a97-9452-768f6da380e4',
      'nickname': 'R1quelme',
      'avatar': 'https://distribution.faceit-cdn.net/images/53c7b351-fdec-4885-9396-b5fd06f8ee41.jpeg',
      'skill_level': 7,
      'game_player_id': '76561198400098616',
      'game_player_name': 'R1quelme',
      'faceit_url': 'https://www.faceit.com/{lang}/players/R1quelme'}]}},

In [21]:
all_matches_mb = asizeof.asizeof(all_matches) / (1024 ** 2)
print(f"final_df: {all_matches_mb:.2f} MB")

final_df: 9.27 MB

In [22]:
import requests

session = requests.Session()
session.headers.update({
    "Authorization": f"Bearer {API_KEY}",
    "Accept": "application/json"
})

stats_data = []

for i, match in enumerate(all_matches, 1):
    match_id = match["match_id"]
    started_at = match["started_at"]

    url = f"https://open.faceit.com/data/v4/matches/{match_id}/stats"
    r = session.get(url)

    if r.status_code in (403, 404):
        stats_data.append({
            "_id": match_id,
            "started_at": started_at,
            "stats_missing": True,
            "status_code": r.status_code,
            "stats": None
        })
        print(f"{i}/{len(all_matches)} | {r.status_code} skipped", end="\r")
        continue

    r.raise_for_status()

    stats_data.append({
        "_id": match_id,
        "started_at": started_at,
        "stats_missing": False,
        "status_code": 200,
        "stats": r.json()
    })

    print(f"{i}/{len(all_matches)} | fetched", end="\r")

print("\nDone")
print("200:", sum(x["status_code"] == 200 for x in stats_data))
print("403:", sum(x["status_code"] == 403 for x in stats_data))
print("404:", sum(x["status_code"] == 404 for x in stats_data))

864/864 | fetchedped
Done
200: 863
403: 0
404: 1

In [33]:
all_used_ids = set()

for row in aggregated.to_dicts():
    all_used_ids.update(row["match_ids_15d"])
    all_used_ids.update(row["match_ids_30d"])

print("Unique matches used:", len(all_used_ids))
print("Original stats_data:", len(stats_data))
print("Difference:", len(stats_data) - len(all_used_ids))

Unique matches used: 181
Original stats_data: 864
Difference: 683

In [34]:
used_ids = set()

for row in aggregated.to_dicts():
    used_ids.update(row["match_ids_15d"])
    used_ids.update(row["match_ids_30d"])

unused = stats_df.filter(
    ~pl.col("_id").is_in(list(used_ids))
)

print(unused.select("_id", "started_at").sort("started_at"))

shape: (682, 2)
┌─────────────────────────────────┬────────────┐
│ _id                             ┆ started_at │
│ ---                             ┆ ---        │
│ str                             ┆ i64        │
╞═════════════════════════════════╪════════════╡
│ 1-394c95a9-4ad5-41cf-ba0e-5764… ┆ 1780872365 │
│ 1-a494b23b-83cc-4144-9b94-9afa… ┆ 1780875854 │
│ 1-3fb2b4a3-546e-4e9c-88fa-9902… ┆ 1780877446 │
│ 1-8c41fc72-a07a-49de-8c43-b75f… ┆ 1780880535 │
│ 1-b41216a4-10d5-43e3-af39-98bc… ┆ 1780954763 │
│ …                               ┆ …          │
│ 1-5b3ed2ba-a522-47b8-ad40-7da8… ┆ 1789497221 │
│ 1-f68c4de6-8b45-478f-9160-3ad6… ┆ 1789499601 │
│ 1-d647c6e1-cb1e-4602-9aca-6fbc… ┆ 1789501859 │
│ 1-feaa8570-aed9-48ed-a4e8-5a40… ┆ 1789504531 │
│ 1-4f52c127-1de4-408c-a4b6-b482… ┆ 1789506830 │
└─────────────────────────────────┴────────────┘

In [35]:
aggregate_statistics(matches_fetch_df, stats_df)

shape: (1, 6)
┌─────────────────┬────────────┬────────────────┬───────────────┬─────────────────┬────────────────┐
│ _id             ┆ started_at ┆ fifteen_window ┆ thirty_window ┆ match_ids_15d   ┆ match_ids_30d  │
│ ---             ┆ ---        ┆ ---            ┆ ---           ┆ ---             ┆ ---            │
│ str             ┆ i64        ┆ i64            ┆ i64           ┆ list[str]       ┆ list[str]      │
╞═════════════════╪════════════╪════════════════╪═══════════════╪═════════════════╪════════════════╡
│ 1-d98000ad-ef4a ┆ 1789477665 ┆ 1788181665     ┆ 1786885665    ┆ ["1-623c3411-19 ┆ ["1-96362b0e-a │
│ -460a-ac15-ca45 ┆            ┆                ┆               ┆ 62-455f-ae79-77 ┆ e99-4457-ba80- │
│ …               ┆            ┆                ┆               ┆ …               ┆ ed…            │
└─────────────────┴────────────┴────────────────┴───────────────┴─────────────────┴────────────────┘

In [ ]:
aggregated_df = aggregate_statistics(


    , stats_df).to_dicts()

stats_lookup = dict(
    zip(
        stats_df["_id"].to_list(),
        stats_df["started_at"].to_list()
    )
)

for row in aggregated_df:

    anchor_time = row["started_at"]
    fifteen = row["fifteen_window"]
    thirty = row["thirty_window"]

    actual_15 = set(row["match_ids_15d"])
    actual_30 = set(row["match_ids_30d"])

    expected_15 = {
        match_id
        for match_id, t in stats_lookup.items()
        if fifteen <= t < anchor_time
    }

    expected_30 = {
        match_id
        for match_id, t in stats_lookup.items()
        if thirty <= t < fifteen
    }

    assert actual_15 == expected_15, f"15d WRONG for {row['_id']}"
    assert actual_30 == expected_30, f"30d WRONG for {row['_id']}"
    assert actual_15.isdisjoint(actual_30), f"OVERLAP for {row['_id']}"

print("All joins/windows are correct.")

SyntaxError: invalid syntax (3495522423.py, line 4)